// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjNFwLPQcQjUXPpMWO5fwZlKibaL8sajc',
    appId: '1:968226273179:web:744ad4c3ff815f9202133e',
    messagingSenderId: '968226273179',
    projectId: 'chatie-e3450',
    authDomain: 'chatie-e3450.firebaseapp.com',
    storageBucket: 'chatie-e3450.appspot.com',
    measurementId: 'G-Z08ZPMMMY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2uWjawlJUquvaH7nI7AvmpJ91JTB3tFI',
    appId: '1:968226273179:android:1c341bae9b84a62102133e',
    messagingSenderId: '968226273179',
    projectId: 'chatie-e3450',
    storageBucket: 'chatie-e3450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxoI48icojMbsEWBmJcdP00x47NBzk6eg',
    appId: '1:968226273179:ios:9bcfdd355765b69302133e',
    messagingSenderId: '968226273179',
    projectId: 'chatie-e3450',
    storageBucket: 'chatie-e3450.appspot.com',
    iosBundleId: 'com.example.chatie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxoI48icojMbsEWBmJcdP00x47NBzk6eg',
    appId: '1:968226273179:ios:24c47b73e379fa5a02133e',
    messagingSenderId: '968226273179',
    projectId: 'chatie-e3450',
    storageBucket: 'chatie-e3450.appspot.com',
    iosBundleId: 'com.example.chatie.RunnerTests',
  );
}
